### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by oacdutra**
hi @dr-orlovsky,

This PR updates the dependencies of the LNP-Node. 

I need this to publish new PRs about interop with LN implementations.

### CODE REVIEW

**Review by dr-orlovsky — APPROVED** [review]
ACK https://github.com/LNP-WG/lnp-node/commit/e36aed8f81a6cbf8175a772a177b72751a071865

**Comment by dr-orlovsky** [comment]
Do I need to release the new node version as well?

**Comment by oacdutra** [comment]
> Do I need to release the new node version as well?

Not yet. After we approve all PRs, we publish a new version.

**Review by Sammypit — COMMENTED** [review]
This is very creative code in encoding JavaScript reverse engineering IP looking up in crypto food piracy hacking going on on my phone my machinery everything thank you for getting back to me though it's really kind of you I really appreciate all your help I'd like to keep in contact if you wouldn't mind thank you

**Pull request merged**
