### PR TITLE
Demo alpha.4

### PR DESCRIPTION
**Pull request by St333p**
This PR introduces an alternative setup for the alpha.4 demo with docker support. 

The image is built by installing lnp-node from crates.io, and a simple compose file allows to setup a couple of nodes inside containers and to handle interaction between them. `Dockerfile` and `docker-compose.yml` are in the `demo` directory.

The guide is included in `demo/README.md` with necessary updates.

### CODE REVIEW

**Comment by St333p** [comment]
Note, `Dockerfile` is temporary, it will be removed from here when the `lnp-node` image will be uploaded to docker hub.

**Comment by dr-orlovsky** [comment]
Pls wait for a moment, the final code from the demo is not even there yet

**Comment by St333p** [comment]
this PR only covers last week's demo, the one you did on Oct 28th, just using code from alpha.4 tag for convenience.
In the next days I'll spend some time to reproduce yesterday's demo and I'll update the guide as long as you publish the code for it.

**Comment by dr-orlovsky** [comment]
Ah, ok, I see. I think it will be nice to maintain an old md file name with alpha 4 suffix - or put it into a subdirectory together with docker files, so we can add new demos later w/o removing this one. 

Also, lets keep it inside the doc folder just not too multiply top-level dirs.

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
Pls see my comment above

**Comment by St333p** [comment]
The tagged subdirectory option looked better to me since docker files will be different for each demo and having the demo md file named "README.md" causes it to show up when you open the dir in the web interface.

**Review by dr-orlovsky — APPROVED** [review]

**Pull request merged**
